name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        rust:
          - nightly
          - beta
          - stable

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - name: Build
        run: |
          cargo build --no-default-features --verbose
          cargo build --all-features --verbose
          cargo build --benches --verbose
      - name: Run tests
        run: cargo test --all-features --no-fail-fast --verbose --all -- --nocapture
        env:
          RUST_BACKTRACE: 1
